package com.xyz.shortener.entity;

import org.springframework.context.annotation.ComponentScan;

import javax.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity(name = "url")
@Table(name = "url")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class URL {
    private Long id;

    @Column(name = "real_url")
    private String realUrl;

    @Column(name = "user_id")
    private Integer userId;

    @Column(name = "fake_url")
    private String fakeUrl;

    public URL(String realUrl, Integer userId) {
        this.realUrl = realUrl;
        this.userId = userId;
    }

    public URL(String realUrl, String fakeUrl, Integer userId) {
        this.realUrl = realUrl;
        this.userId = userId;
        this.fakeUrl = fakeUrl;
    }

    /**
     * @return Autogenerated Id for the url record in the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return id;
    }
}
