version: '3.1'

services:
  server:
    container_name: urlredirect-springboot
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://myredirectdb:3306/url_redirect_db
    ports:
      - "8081:8090"
    networks:
      - urlshortener-network
    depends_on:
      - db

  db:
    container_name: myredirectdb
    build:
      context: ./database
    volumes:
      - ./database/data:/var/lib/mysql
    networks:
      - urlshortener-network
    environment:
      - MYSQL_ROOT_PASSWORD=pa55w0rd
      - MYSQL_DATABASE=url_redirect_db
      - MYSQL_USER=urlshortener
      - MYSQL_PASSWORD=123456
    ports:
      - '3307:3306'

networks:
  urlshortener-network:
