version: '3.1'

services:
  server:
    container_name: urlshortener-springboot
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqlurldb:3306/urldb
    ports:
      - "8081:8090"
    networks:
      - urlshortener-network
    depends_on:
      - db

  db:
    container_name: mysqlurldb
    build:
      context: ./database
    volumes:
      - ./database/data:/var/lib/mysql
    networks:
      - urlshortener-network
    environment:
      - MYSQL_ROOT_PASSWORD=pa55w0rd
      - MYSQL_DATABASE=urldb
      - MYSQL_USER=urlshortener
      - MYSQL_PASSWORD=123456
    ports:
      - '3306:3306'

networks:
  urlshortener-network:
