package com.xyz.redirect.entity;

import javax.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity(name = "url")
@Table(name = "url")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class URL {
    private Long id;

    @Column(name = "real_url")
    private String realUrl;

    @Column(name = "fake_url")
    private String fakeUrl;

    @Column(name = "ref_id")
    private Long refId;

    public URL(String fakeUrl) {
        this.fakeUrl = fakeUrl;
    }

    public URL(String realUrl, String fakeUrl) {
        this.realUrl = realUrl;
        this.fakeUrl = fakeUrl;
    }

    /**
     * @return Autogenerated Id for the url record in the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return id;
    }
}
