package com.xyz.redirect.entity;

import javax.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity(name = "url_access")
@Table(name = "url_access")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class URLAccess {
    private Long id;

    @Column(name = "access_time")
    private java.sql.Timestamp accessTime;

    @Column(name = "fake_url")
    private String fakeUrl;

    public URLAccess(String fakeUrl) {
        this.fakeUrl = fakeUrl;
    }

    /**
     * @return Autogenerated Id for the url record in the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public Long getId() {
        return id;
    }
}
